### ISSUE TITLE
Incompatible with Nx > 17.0.3

### ISSUE THREAD

**Issue by jackgraves** [toolsplus/nx-forge#53]
The Forge Nx plugin operates correctly in versions up to and including **17.0.3**, but any versions above this put the generated file 'index.js' in the wrong directory, preventing the plugin from being used.

**Comment by tbinna** [comment]
Hey @jackgraves thanks for the report and the PR! I looked at this and managed to reproduce the issue. Will add some comments to your PR directly.

**Comment by tbinna** [comment]
Hey @jackgraves, I am closing this PR in favor of #56. You should be able to test out the changes using `nx migrate @toolsplus/nx-forge@3.0.0-beta.1` and follow the CLI instructions (run `npm i`, then `nx migrate --run-migrations`, then delete the `migrations.json` file).

Just a heads-up that I have noticed an issue with the manifest dependency that I will try to fix tomorrow.
